name: Update Zip Code
on: 
  schedule:
    # 12:00(JST) on the first day of every month
    - cron: '0 3 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - name: Update zip_codes.csv
      run: | 
        npm install
        npm run update-zipcode
    - name: Build
      run: |
        npm run build
    - name: Commit
      run: |
        git config --global user.email "s1r.aria.azureglo@gmail.com"
        git config --global user.name "s1r-J"
        git config --global pull.ff only
        git add .
        git commit -m "Update $(date +'%Y-%m-%d')"
        git pull origin main
        git push origin main
    - name: Publish
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
